"""WAP THAT HAS record of 10 emp wheere emp id id used as a key and salary as value.
 so find out the total number of emp having 
 aslry greater than 30000
display the list of emp whose salary is bwlow 20000"""


emp = {}

#for i in range(10):
# id = input("Enter ID: ")
sal = int(input("Enter salary: "))
    
    #emp[id] = sal

#print(emp)"""
    
emp[id] =sal

count=0
for i in range(10):
     if sal>30000:
        count+=1
        print(count)

     elif sal <20000:
        print(emp)
       
        

